name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0
  modal_progress_hud: ^0.1.3
  flutter_launcher_icons: "^0.7.5"
  google_sign_in: ^4.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - images/
  - images/pinguino.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"